[package]
name = "boost"
version = "0.1.0"
authors = ["Jake Sandler <jsandler18@gmail.com>"]

[dependencies]
regex = "0.2"
byteorder = "1"
rand = "0.3"
sha1 = "0.2.0"
bitflags = "0.9.0"
clap = "2.25.0"
